### ISSUE TITLE
按照你的方法做的，但是报空指针错误

### ISSUE THREAD

**Issue by hejunv** [bestruirui/WeChatPush#2]
热登陆失败，尝试免扫码登录
访问下面网址扫描二维码登录
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5fd624]

goroutine 1 [running]:
bestrui/wechatpush/mail.SendEmail({0x715388, 0x6}, {0xc0003a0120, 0x2f})
	/app/mail/mail.go:61 +0x424
bestrui/wechatpush/openwechat.PrintlnQrcodeUrl({0xc000349210, 0xc})
	/app/openwechat/bot.go:440 +0x7a
bestrui/wechatpush/openwechat.(*LoginChecker).CheckLogin(0xc0000b3ce0)
	/app/openwechat/bot_login.go:251 +0x50
bestrui/wechatpush/openwechat.(*ScanLogin).checkLogin(0xc00005a380?, 0x79e708?, {0xc000349210?, 0x7f85c3320248?})
	/app/openwechat/bot_login.go:185 +0x91
bestrui/wechatpush/openwechat.(*ScanLogin).Login(0xc000014350?, 0xc0000e2000?)
	/app/openwechat/bot_login.go:172 +0x58
bestrui/wechatpush/openwechat.(*Bot).login(0xc0000e2000, {0x79c100, 0xc000014350})
	/app/openwechat/bot.go:62 +0xab
bestrui/wechatpush/openwechat.(*Bot).Login(...)
	/app/openwechat/bot.go:74
bestrui/wechatpush/openwechat.(*RetryLoginOption).OnError(0x40e59b?, 0xc0000e2000, {0x79c140?, 0x96e750?})
	/app/openwechat/bot_login.go:107 +0x85
bestrui/wechatpush/openwechat.BotOptionGroup.OnError({0xc000014330?, 0xc0000e2000?, 0xc000014340?}, 0xc0000e2000, {0x79c140, 0x96e750})
	/app/openwechat/bot_login.go:61 +0x70
bestrui/wechatpush/openwechat.(*Bot).login(0xc0000e2000, {0x79c040, 0xc000014340})
	/app/openwechat/bot.go:63 +0xcf
bestrui/wechatpush/openwechat.(*Bot).PushLogin(...)
	/app/openwechat/bot.go:94
main.main()
	/app/main.go:21 +0x3c6

**Comment by hejunv** [comment]
用以下命令启动的，邮箱使用Python发邮件试过了，可以正常发。
docker run -d \
	--name WxPush \
	-e FROM_NAME=30000000@qq.com#发送者邮箱 \
	-e FROM_ADDRESS=mimi#发送者名字 \
	-e TO_NAME=iamgod#收件人名字 \
	-e TO_ADDRESS=100000000@qq.com#收件人邮箱 \
	-e SMTP_SERVER=smtp.exmail.qq.com \
	-e SMTP_PORT=465 \
	-e USERNAME=300000000@qq.com#smtp的邮箱 \
	-e PASSWORD=e00000000c#smtp的邮箱密码 \
	-v ./WxPush:/app/data \
	bestrui/wxpush:latest
# 如果镜像拉取速度慢，可以使用代理`docker.nju.edu.cn/bestrui/wxpush:latest`

**Comment by hejunv** [comment]
使用的一下命令启动。账号密码用Python邮件验证过，可以正常发邮件
docker run -it \
	--name WxPush \
	-e FROM_NAME=3000000005@qq.com \
	-e FROM_ADDRESS=3000000005@qq.com \
	-e TO_NAME=米米 \
	-e TO_ADDRESS=100000000@qq.com \
	-e SMTP_SERVER=smtp.exmail.qq.com \
	-e SMTP_PORT=465 \
	-e USERNAME=3000000005@qq.com \
	-e PASSWORD=e00000000c \
	-v ./WxPush:/app/data \
	bestrui/wxpush:latest

**Comment by hejunv** [comment]
smtp.exmail.qq.com是企业邮箱，换成普通邮箱就正常了
